/**
 * This file is a configuration file generated by the `Template` extension on `vscode`
 * @see https://marketplace.visualstudio.com/items?itemName=yongwoo.template
 */
module.exports = {
  // You can change the template path to another path
  templateRootPath: "./.templates",
  // After copying the template file the `replaceFileTextFn` function is executed
  /**
   *
   * @param {string} fileText
   * @param {string} templateName
   * @param {any} utils
   */
  replaceFileTextFn: (fileText, templateName, utils) => {
    // @see https://www.npmjs.com/package/change-case
    const { changeCase } = utils;

    let templateNameWithoutSuffix = templateName;
    if (templateName.lastIndexOf(".") > templateName.lastIndexOf("/")) {
      templateNameWithoutSuffix = templateName.substring(
        0,
        templateName.lastIndexOf(".")
      );
    }
    // You can change the text in the file
    return fileText
      .replace(/__templateName__/g, templateNameWithoutSuffix)
      .replace(
        /__templateNameToCamelCase__/g,
        changeCase.camelCase(templateNameWithoutSuffix)
      )
      .replace(
        /__templateNameToPascalCase__/g,
        changeCase.pascalCase(templateNameWithoutSuffix)
      )
      .replace(
        /__templateNameToParamCase__/g,
        changeCase.paramCase(templateNameWithoutSuffix)
      );
  },
  renameFileFn: (fileName, templateName, utils) => {
    if (
      !fileName
        .split("/")
        .at(-1)
        .includes(".")
    ) {
      const l = templateName.split("/").at(-1);
      if (l.includes(".")) {
        fileName += l.substring(l.lastIndexOf("."));
      }
    }

    const { path } = utils;
    const { base } = path.parse(fileName);
    return base.replace(/__templateName__/gm, templateName);
  },
  renameSubDirectoriesFn: (directoryName, templateName, _utils) => {
    const { changeCase } = _utils;
    const newDirectoryName = changeCase.paramCase(templateName);
    return directoryName.replace(/__templateName__/g, newDirectoryName);
  },
};
